receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8890']
            - targets: ['localhost:8889']
            - targets: ['localhost:8888']

exporters:
  tencentcloud_logservice:
      # LogService's Endpoint, https://cloud.tencent.com/document/product/614/18940
      # set cls.{region-id}.tencentcloudapi.com, eg cls.ap-beijing.tencentcloudapi.com;
    endpoint: "cls.ap-beijing.tencentcloudapi.com"
    # LogService's LogSet ID
    logset: "demo-logset"
    # LogService's Topic ID
    topic: "demo-topic"
    # TencentCloud secret id
    secret_id: "demo-secret-id"
    # TencentCloud secret key
    secret_key: "demo-secret-key"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [tencentcloud_logservice]
